version: '3.8'

services:
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis_data:/data

  bot:
    build: .
    command: python bot/bot.py
    restart: always
    env_file: .env
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A worker.tasks worker --loglevel=info -Q default --concurrency=2
    restart: always
    env_file: .env
    depends_on:
      - redis

  accelerator:
    build: .
    command: celery -A worker.tasks worker --loglevel=info -Q high_priority --concurrency=8
    restart: always
    env_file: .env
    depends_on:
      - redis

volumes:
  redis_data:
